### PR TITLE
Remove unused apps

### LINKED ISSUE #133: Heatmap is broken
when open Heatmap, it fails already on attempt to open with stack trace, apparently error handling is not present at all

```
ValueError: Custom tiles must have an attribution.
Traceback:

File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/user/app/pages/4_🔥_Heatmap.py", line 25, in <module>
    m = leafmap.Map(center=[40, -100], zoom=4, tiles="stamentoner")
File "/usr/local/lib/python3.10/site-packages/leafmap/foliumap.py", line 91, in __init__
    super().__init__(**kwargs)
File "/usr/local/lib/python3.10/site-packages/folium/folium.py", line 323, in __init__
    tile_layer = TileLayer(
File "/usr/local/lib/python3.10/site-packages/folium/raster_layers.py", line 140, in __init__
    raise ValueError("Custom tiles must have an attribution.")
```

### PR DESCRIPTION
**Pull request by giswqs**
Fix #133 #132

### CODE REVIEW

**Comment by aytvill** [comment]
it looks like fixes has been done, but code isn't deployed - at least provided [URL](https://huggingface.co/spaces/giswqs/Streamlit) even after forced refresh (Ctrl+R) still shows both apps and they fail same way as described in #133 #132

**Comment by giswqs** [comment]
I just fixed it. Should be available shortly.

**Comment by aytvill** [comment]
Ahem... have you tried it yourself? Here on my side link
https://huggingface.co/spaces/giswqs/Streamlit
starts and then after short time gives dialog with 404 error
Screenshot 2024-07-02 at 19-51-14 Streamlit - a Hugging Face Space by giswqs

**Comment by giswqs** [comment]
clear browser cache or open it in incognito mode

**Pull request merged**
